name: ra_hotreload
description: Implementation of hot reload feature for the RA server.
version: 0.9.7-pre
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  hotreloader: ^4.2.0
  ra:
    git: https://github.com/ra-api/dart_ra.git

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
